# Generated by Django 4.0.5 on 2022-11-21 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('organization_uuid', models.UUIDField(verbose_name='organization identifier')),
                ('status', models.CharField(choices=[('EDITING', 'EDITING'), ('WAITING', 'WAITING'), ('RENDERING', 'RENDERING'), ('FINISHED', 'FINISHED')], max_length=10, verbose_name='status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to='users.userprofile')),
                ('last_modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name': 'video project',
                'verbose_name_plural': 'video projects',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('position', models.PositiveIntegerField(verbose_name='position')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='users.userprofile')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_line', to='editor.videoproject')),
            ],
            options={
                'verbose_name': 'track',
                'verbose_name_plural': 'tracks',
                'ordering': ('-position',),
                'unique_together': {('project', 'position')},
            },
        ),
    ]
